# 지킬에 오신 것을 환영합니다!
#
# 이 구성 파일은 전체 사이트에 영향을 미치는 설정을 위한 것으로, 한 번만 설정하고 그 이후에는 거의 편집하지 않을 것으로 예상되는 값입니다.
# 이 파일을 자주 편집하는 경우 자주 업데이트해야 하는 데이터에 지킬의 데이터 파일 기능을 사용하는 것을 고려해 보세요.
#
# 기술적인 이유로 'jekyll serve'를 사용하면 이 파일이 *NOT* 자동으로 새로고침됩니다.
# 이 파일을 변경하면 서버 프로세스를 다시 시작해 주세요.

# 사이트 설정
# 새 사이트를 개인화하는 데 사용됩니다.
# HTML 파일을 보면 {{site.title}}, {{site.github_repo}} 등을 통해 액세스할 수 있습니다.
# 원하는 사용자 지정 변수를 만들 수 있으며, 템플릿에서 {{site.myvariable }}을 통해 액세스할 수 있습니다.
locale: "ko-KR"
masthead_title: "AiDALab 강의자료"
title: "AiDALab Lectures"
subtitle: "Version 1.0"
description: "AiDALab 강의 자료 개발 블로그"
baseurl: "" # 사이트의 하위 경로(예: /blog)
url: "https://aidalabs.github.io" # 사이트의 기본 호스트 이름 및 프로토콜(예: http://example.com )

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# 회귀 테스트
# 기본적으로 /docs/tests 페이지는 사이트가 구축될 때 제외됩니다.
# 이를 포함하려면 위의 관련 항목에 댓글을 달면 됩니다.
# 다음 줄에 댓글을 달지 않는 것은 작동하지 않습니다 - https://github.com/jekyll/jekyll/issues/4791 참조
# include: ["docs/tests/"]

# 제목 대신 표시될 로고로 path/url 설정
logo: "/assets/images/aidalab_logo.png"

# 사이트 검색 활성화 또는 비활성화
# 참(기본값) 또는 거짓을 지원합니다.
search_enabled: true
search:
  # 페이지를 개별적으로 검색할 수 있는 섹션으로 분할
  # Supports 1 - 6, default: 2
  heading_level: 2
  # 검색 결과당 미리보기 최대 수
  # Default: 3
  previews: 2
  # 미리보기에서 일치하는 단어 앞에 표시할 최대 단어 수
  # Default: 5
  preview_words_before: 3
  # 미리보기에서 일치하는 단어 뒤에 표시할 최대 단어 수
  # Default: 10
  preview_words_after: 3
  # 검색 토큰 구분 기호 설정
  # Default: /[\s\-/]+/
  # 예: 하이픈으로 표시된 검색어에 대한 지원 사용
  tokenizer_separator: /[\s/]+/
  # 검색 결과에 상대 URL 표시
  # 참(기본값) 또는 거짓을 지원합니다.
  rel_url: true
  # 모든 페이지의 오른쪽 하단에 표시되는 검색 버튼을 활성화하거나 비활성화합니다.
  # 참 또는 거짓 지원(기본값)
  button: false

# 제목 앵커 활성화 또는 비활성화
heading_anchors: true

# 오른쪽 상단 탐색을 위한 보조 링크
aux_links:
  "AiDALabs on GitHub":
    - "//github.com/aidalabs"

# 새 탭에서 Aux 링크를 엽니다. 기본값은 거짓입니다
aux_links_new_tab: false

# 탐색 링크 정렬 순서
# nav_sort: case_insensitive # 기본값, 0에 해당함
nav_sort: case_sensitive # 소문자 앞에 정렬된 대문자

# 푸터 콘텐츠
# 모든 페이지의 기본 콘텐츠 하단에 표시됩니다.

# 상단 링크로 돌아가기
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020~ AiDALab."

# 푸터가 마지막으로 편집된 타임스탬프
last_edit_timestamp: true # 편집 시간 표시 또는 숨기기 - 페이지의 전면에 'last_modified_date'가 정의되어 있어야 합니다
last_edit_time_format: "%b %e %Y at %I:%M %p" # 루비의 시간 형식을 사용합니다: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# 푸터 "GitHub에서 이 페이지 편집" 링크 텍스트
gh_edit_link: true # 이 페이지 링크 표시 또는 숨기기 편집
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/aidalabs" # 사용자 저장소의 깃허브 URL
gh_edit_branch: "master" # 문서(docs)가 제공되는 지점
# gh_edit_source: docs # 사용자 소스파일의 출처
gh_edit_view_mode: "tree" # 사용자가 편집기에 즉시 참여하도록 하려면 "tree" 또는 "edit"합니다

# 현재 색상 구성표는 "다크", "라이트"/닐(기본값) 또는 사용자 정의 구성표만 지원합니다.
color_scheme: nil

# Google Analytics Tracking (optional): AiDALab의 추적코드
ga_tracking: UA-41800303-1
ga_tracking_anonymize_ip: true # GDPR 준수 Google 분석 설정 사용(기본적으로 true/nil)

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
